name: flutter_lokalise
version: 1.0.0
description: >
  A tool to download translation files from Lokalise and convert them to .arb files.
homepage: https://github.com/meniga/flutter_lokalise

environment:
  sdk: ">=2.18.2 <3.0.0"

executables:
  flutter_lokalise:

dependencies:
  archive: 3.3.4
  args: 2.3.1
  freezed_annotation: 2.1.0
  json_annotation: 4.6.0
  http: 0.13.5
  logging: 1.1.0
  path: 1.8.2
  quiver: 3.1.0
  yaml: 3.1.1

dev_dependencies:
  build_runner:
  freezed: 2.1.0+1
  json_serializable: 6.3.1
  matcher: 0.12.13
  mock_web_server: 5.0.0-nullsafety.1
  mockito: 5.3.2
  pedantic: 1.11.1
  remove_from_coverage: 2.0.0
  test: 1.22.0
